id: PF9307F98
initial_creation_type: input
source_metadata:
  Title: Kāṇhapādasya dohākoṣaḥ
  Editor: P. C. Bagchi
  Publisher: Metropolitan Printing & Publishing House, Ltd.
  Place of Publication: Calcutta
  Year: '1938'
  Kāṇhapādasya dohākoṣaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2015'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:57:25.969444'
last_modified_at: '2022-03-08T16:57:25.969452'
